### Wk9:DAY3 - INTRODUCTION TO LINEAR ALGEBRA

Our linear Algebra journey starts with matrices.
A matrix is a collection of numbers ordered in rows and columns.
E.G
[5 12 6
-3 0 14]
Each of the values is an ELEMENT of the matrix. Our matrix is a total of 6 elements. We normally denote a matrix with apital letter e.g A. Our matrix A has 2 rows and 3 columns.In linear Algebra, rows and columns are the dimentions of the matrix. A is a 2*3 matrix. Matrices seem similar to tables and spredsheets. Matrices are main characters in mathematical operations.

Two matrices can be added, subtracted, multiplied, and divided. So linear Algebra is similar to Algebra in the types of operations they run, but defers from when and how these operations are implemented.

A matrix can only contain numbers, symbols, or expressions. The later 2 are nothing more than a generalised representation of numbers. A collection of these 6 symbols B = [a b c 
                     d e f]
show a difft 2*3 matrix.
C has 4 elements and it's a 2*2 matrix; C=[a-x  b+5
                                          d+e    e]
These are not values but expressions.

Size of a matrix:
A matrix can be of any size.In the general case, we are talking about an m*n matrix. If A is an m*n matrix, it means it has m rows and n columns. aij is ith row and jth column. To fill in a matrix, you start from a11, a12, a13........a1n to finish the 1st row. In most programming languages, arrays start from 0 rather than 1.

#### Scalars and Vectors

Matrices are 2 dimentional objects as they have rows and columns (2D). 
A matrix with 1 row and 1 column [a11]. It contains a single element and it's called Scalars.
All numbers we know from algebra are referred to as scalars in linear algebra.
[15]; [1]; [2]; [-5]; are all scalars. 

Since scalars are objects with no dimensions, they have important properties we'll have to examine later on. 

Vectors:
Vectors are also very common objects in linear algebra. They exist somewhere btw scalars and matrices as they have one dimention.

Scalar[15]; Vector[5 -2 4] as a column. Matrix [5 12 6
                                               -3 0 14]
Vector is a 3*1 matrix. Its single dimention is the number of rows that it has.Since a scalar is basically a number, A vector is practically the simplest linear algebraic object.

Given the many applications of vectors, they have the special name and are often examined as a seperate object.
Moreover, it is more common to view a matrix as a collection of vectors rather than a vector as a special case of a matrix. Each column of a matrix is a vector.

Generally, there are 2 types of vectors; column vectors and row vectors. Often we are interested in the number of elements a vector contains. We refer to that number as the length of a vector. [5 
                                                6
                                                4]
The 1st vector has a length of 3, and the 2nd a length of 4 [3 4 5 8] . 

In the general case, a vectors length can be designated as m. So, a column vector will have dimentions m*1 and the row vector, 1*m.
Regarding the notation, the elements of a vector x, will be x1, x2, ....xm.

In summary, we have matrices that are 2 dimentions, m*n (2D). Vectors that have a single dimention m*1 (1D). And scalars that have no dimentions 1*1. (0D).

#### Linear Algebra and Geometry

Mathematics works based on analogies. With linear algebra, that's extremely relevant. We said a scalar (x) has no dimentions(OD), what else has no dimensions? well, the geometrical idea of a point(.) (OD). A point is the simplest object in terms of geometry.It has no direction and no size. A scaler is like a point. 

Then we have vectors;

a vector has one dimention(1D) m*1. 

It is like a line. H/ever, it has a direction. It can be oriented in many ways. We can plot the line on a 2 dimentional plain. H/ever, to get into 2D, we need smth else. The only way to get from a line to a plain is by crossing it with another line. So 2 dimentional space is defined by 2 lines. 2 lines mean 2 vectors. [x1, x2, ....xm]  [y1, y2.....ym] in vertical form. 2D lines are \/ 2 arrows.

In linear algebra, a matrix is a collection of vectors. D4, any 2 dimentional plain can be represented by a matrix(m*2) x1    y1
                                                      x2    y2
                                                      .      .
                                                      .      . 
                                                      xm    ym

Let's explore the 2 dimensional plain;

If I want to represent a vector, say 2,5, it will be a long line from the origin of the plain to the point of position 2,5. The direction is always from the origin of the graph to the end point. The vector -2,-5 will be exactly the opposite of the 1st one. Each of the vectors has a direction determined by its values. [2 5]  [-2 -5].  [-2 3]. 

The 1st vector is [1 0]  and the 2nd, [0 1]. Taking the 2 vectors together, we can create a matrix. [1 0
                         0 1]
                         
This matrix is made up of small portions of the 2 axis, x and y. Most important is if I remove everything else from the graph, this matrix will define the 2D plain we were looking at. Actually, every 2 vectors we take will define the 2 matrices we were looking at. 

Find online 3D vector plotter by academo.org You can specify each vector of interest and fiddle with the plot.


### Scalars, Vectors, and Matrices as Python Arrays

#### How to code Matrix, Vectors, and Scalars

#### Import the relevant libraries

The simplest and most flexible way to work with scalars, vectors, and matrices in Python is by using array. Moreover, we'll use the numpy functionalities as they are optimised for such operations.

In [14]:
import numpy as np

#### Declaring Scalars, Vectors, and Matrices

#### scalars

In [15]:
# Let's declare a scalar

s = 5

In [16]:
s

5

In [17]:
# Let's declare a vector like [5 -2 4]
# note there are round brkts for thr np.array mtd, and square brkt for the vector itself. 

v = np.array([5, -2, 4])


In [18]:
# By default, v is a row vector
v

array([ 5, -2,  4])

#### Matrix

In [19]:
# This matrix contains 2 vectors

m = np.array([[5,12,6],[-3,0,14]])

In [20]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

#### Data Types

type(a) returns the data type of a given variable

In [21]:
type(s)

int

In [22]:
type(v)

numpy.ndarray

In [24]:
type(m)

numpy.ndarray

In [ ]:
# n-dimensional array
# v is a 1-dimensional array
# m is a 2-dimensional array
# for s to be consistent with the others, we can declare it a s an array

In [25]:
s_array = np.array(5)
s_array

array(5)

In [26]:
type(s_array)

numpy.ndarray

#### Data Shapes

For all practical purposes, in Python and within numpy, integers or floats and arrays with 1 element, behave in the same way regarding linear algebraic operations.  

shape returns the shape (dimensions) of a variable.

In [27]:
m.shape

(2, 3)

In [28]:
# The output 3, indicates that v has 3 elements stored in order.

v.shape

(3,)

#### Creating a column vector

reshape gives an array a new shape, without changing its data. We can use the reshape mtd to create a row or a column vector.

In [29]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [30]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [31]:
# We can check the shape of s. It'll return an error as int objects don't have shape.

s.shape

AttributeError: 'int' object has no attribute 'shape'

In [32]:
# Trying the same mtd on s_array, we simply have parenthesis bcos a scalar is a zero dimensional object, thus it has no shape.

s_array.shape

()

#### What is a Tensor?

Tensorflow is developed by google  to work with tensors. The mathematical concept of a tensor is explained thus;
A scalar has the lowest dimensionanility and is always 1 by 1.[15]. It can be thought of as a vectorof length 1 or a 1 by 1 matrix. It is followed by a vector and each element of the vector is a scalar.[x1, x2......xm]. The dimensions of a vector is nothing but 1*1 ie m x 1 or 1 x m matrices.

Then we have matrices which are nothing but a collection of vectors. The dimesions of a matrix are m x n. In other words, a matrix is a collection of m vectors of dimensions m x 1 or m vectors of dimensions m x 1. Since scalars make up vector, you can also think of a matrix as a collection of scalars too. 

A tensor is the most general concept. Scalars, vectors and matrices are all tensors of rank 0, 1 and 2 respectively. Tensors are simply a generalisation of the concepts we have seen so far. An object we haven't seen is a tensor of rank 3. Its dimensions are k x m x n. It can be thought of as a collection of matrices. In terms of programming, a tensor is no difft than an ndarray. Innfact, tensors can be stored in ndarrays, and that's how we often deal with issue.

Let's create a tensor out of 2 matrices;
Our 1st matrix m1 will be from the 1st e.g. m2 will be difft with the elements 9 8 7 and 1 3 -5. Then we create an array T with 2 elements m1 and m2. After printing T, we realise it contains both matrices. 


#### Import the relevant libraries

In [2]:
import numpy as np

#### Creating a tensor

In [3]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [5]:
t = np.array([m1,m2])

In [6]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### Checking its Shape

In [7]:
t.shape

(2, 2, 3)

#### Manually Creating a Tensor

In [8]:
t_manual = np.array([[[ 5, 12, 6], [-3, 0, 14]], [[ 9, 8, 7], [1, 3, 5]]])

In [9]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3,  5]]])

### Adding and Subtraction

We can add or subtract matrices.

ADDITION:

This an easy operation. There's only one condition. The 2 matrices must have the same dimensions.
Say we have the 2 matrices;
m1 = [5 12 6
      -3 0 14]  
      and
m2 = [9 8 7
      1 3 -5]
      
As you can see, they are both 2 x 3 matrices. If I want to add the 2, I'll add the corresponding entries one with the other. The result is a new 2 x 3 matrix.

M1 + M2 = X



In [ ]:
[ 5 12 6 + [ 9 8 7   = [5+9  12+8  6+7   = [14 20 13
 -3 0 14]    1 3 -5]   -3++1  0+3  14-5]    -2 3 9]

In [ ]:
# For the elements at position 1, we have 5+9, at position 12, we have 12+8, at 13, we have 6+7 etc.

If I want to add the matrices in Python, I will use the plus sign.

#### Import the relevant libraries

In [4]:
import numpy as np

##### Addition

In [5]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [7]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

#### Subtraction

In [8]:
Subtraction is a type of addition, so the same rule applies there.

The 2 matrices have the same dimensions, 2 x 2.

SyntaxError: invalid syntax (3595305287.py, line 1)

In [9]:
[5 3   - [7 -5  = [5-7 3+5   = [-2 8
 -2 4]    3 8]     -2-3 4-8]    -5 -4]

SyntaxError: invalid syntax (3181134123.py, line 1)

For coding, we declare the 2 matrices and find the difference.

#### Difference

In [10]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [11]:
m3

array([[ 5,  3],
       [-2,  4]])

In [12]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [13]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

We can do the same with float as well. The 2 matrices are both 3x2 so they are compatible.

In [14]:
[22.33 -4.73       [131.13 448.29    [-108.8 -453.02
 -203.14 1200.02 -  -340.21 1.06   =  137.07 1198.06
 4.22 234.10]       30.41 424.99]     -26.19 -190.89]

SyntaxError: invalid syntax (2788413219.py, line 1)

In [15]:
m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22, 234.10]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [16]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [17]:
m5 - m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

#### Subtraction of Vectors

Since vectors are 1 dimensional matrices, same rules apply. With vectors, we only care about the length. One way to add them up is; 1st element with 1st element, 2nd with 2nd etc. The result is a vector of length 5 where all entries are 6s.

#### Adding Vectors together

In [18]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [19]:
v1 + v2

array([6, 6, 6, 6, 6])

In [20]:
v1 - v2

array([-4, -2,  0,  2,  4])

#### Errors When Adding Matrices

In [21]:
Scalars are more peculiar than higher dimension objects bcos they are single numbers.
To add scalars we have;

SyntaxError: invalid syntax (1864841930.py, line 1)

#### Import relevant libraries

In [22]:
import numpy as np

#### Addition

##### Addition of Scalars

In [23]:
5 + 5

10

In [24]:
10 - 4

6

##### Addition of matrices

To add vectors and matrices together, the forms must match. we can't add vector of difft lines and matrices with difft dimensions. Such operations are not permitted in linear algebra and python knows that. E.g add a 2x2 matrix with a 2x3 matrix will return an error.

In [25]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

##### Addition of vectors

To add 2 vectors with difft lines, we get the same error.

In [26]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [28]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [29]:
# Mathematically, these operations don't make sense, so they can't be executed.

v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

##### Exceptions (addition with a scalar)

Because of how arrays work in Python and many other languages, we can add scalars to matrices and vectors. If you add 1 to matrix m1, each element in the matrix will increase by 1.

In [30]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [31]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [32]:
# Similarly, if you add 1 to the vector v1, it will be added elementwise.

v1

array([1, 2, 3, 4, 5])

In [33]:
v1 + 1

array([2, 3, 4, 5, 6])

In [34]:
# mathematically this operation is not allowed as the shapes are difft.But in programming or at least in Python, it works.
# The result has a meaning in terms of arrays, but not in terms of linear algebra.
# That is also the diff btw the concepts of nd.array and tensors.

m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [35]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

### Transpose of a Matrix

##### Transposing Vectors

We already know that vectors are either rows or columns. So let x be the column vector [123]. There's a special operation that can turn it into a row vector. We can transpose it. Transposing the column vector 123 will result in a row vector 123. We denote this operation with a letter T as a superscript. X^T. D4, [1
                       2
                       3] T  = [123] and vice versa.
If we transpose X 2ce, we get X.    

1.When we transpose a vector, we are not losing any information. The values are not changing or transforming; only their position is.

2.Transposing the same vector(object) twice, yields the initial vector(object).

3.A 3x1 matrix transposed is a 1x3 matrix.

##### Transposing Matrices

In terms of dimensions, when transposed, and mxn matrix becomes and nxm matrix.

In [ ]:
A = [5 12 6
    -3 0 14]  A^T = [5-3
                     12 0
                     6 14]
# A is a 2x3 matrix, A transposed is a 3x2 matrix. Transposing matrices is transposing a bunch of vectors.

        

##### Import the relevant libraries

In [ ]:
import numpy as np

##### Transposing matrices

array.T returns the transpose of an array (matrix)

In [36]:
A = np.array([[5, 12, 6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [37]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [38]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [39]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [40]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

##### Transposing Scalars

In [41]:
# Any scalar when transposed equals itself.

S = np.array([5])

In [42]:
S.T

array([5])

##### Transposing Vectors

In [43]:
# In python, 1 dimensional arrays don't get transposed.

X = np.array([1,2,3])
X

array([1, 2, 3])

In [44]:
X.T

array([1, 2, 3])

In [45]:
X.shape

(3,)

In [46]:
X_reshaped = X.reshape(1,3)
X_reshaped

array([[1, 2, 3]])

In [47]:
X_reshaped.T

array([[1],
       [2],
       [3]])

#### Dot Product

##### Scalar Multipliction

In [ ]:
[6].[5] = [30]

[10].[-2] = [-20]

To multiply vectors, they must be compatible or have the same length.

[2 8 -4] x [1 -7 3] We can get 2 products; 1. Dot or inner product or Tensor or outer product. Here, we won't be needing the outer product. you can read it up. The dot product is heavily used for multipliation of vectors and matrices. Other names for the dot product are inner or scalar products. We multiply each 2 corresponding elements and find the sum.

In [ ]:
[2     [1
8   .   -7  = [2x1+8x(-7)+(-4)x3] = [-66]
-4]     3]

# As you can see, we multiplied 2 vectors and got a scalar. That's why the dot product is also known as scalar product.
# The dot product is the sum of the products of the corresponding elements

##### import the relevant libraries

In [ ]:
import numpy as np

##### Dot product

In [48]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [49]:
np.dot(x,y)

-66

In [51]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [52]:
np.dot(u,v)

18

##### Scalar x Scalar

In [53]:
np.dot(5,6)

30

In [54]:
np.dot(10,-2)

-20

##### Scalar x Vector

When we multiply a vector with a scalar, we get a vector with the same length.
Multiplication by a scalar does'nt change the shape, but only the scale of the values.

In [55]:
x

array([ 2,  8, -4])

In [56]:
5*x

array([ 10,  40, -20])

### Dot Product of Matrices

##### Scalar x Matrix

In [57]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [58]:
# The shape of a matrix does'nt change, it just gets scaled.

3*A

array([[15, 36, 18],
       [-9,  0, 42]])

We can multiply 2 matrices. But only multiply an m x n matrix with an n x k dimension matrix. The 2nd dimension of the 1st matrix must match the 1st dimension of the 2nd matrix. So we can multiply a 2x3 matrix with a 3x1,2,3....k matrix. As long as the 3s are matching. Similarly, to multiply a 5x7 matrix, compatible matrices for multiplication are; 7x1,2,7....k. For the dimensions of the product itself, we are multiplying an m x n matrix by an n x k matrix, the output is an m x k matrix. For instance, a 2 x 3 . 3 x 6 matrix = 2 x 6 ie A . B = c and  a 3x4 . 4x2 = 3x2 ie A.B = C and a 100x300 . 100x3 = 300x3 ie A . B = C.
How then do we multiply matrices? Let's start with 2 matrices;
                                                                
                                                             

In [ ]:
[2     [1
 8      -7  = [-66]
-4]     3]

# For compatibility: they need to have matching forms.
# To find the dot product, we tranpose the 1st and get a 1x3 matrix of [2 8 -4] x the 3x1 matrix.
# When we have a dot product, we always multiply a row vector times a column vector. The result is a 1x1 form or scalar.
# We reach the scalar by multiplying the corresponding element and summing everything up.

In [ ]:
[5 12 6   .  [2 -1   [ 5x2+ 12x8 + 6x3       [124 -5
 -3 0 14]     8 0   = 5x-1 + 12x0 + 6x0    = 36 3]
              3 0]    -3x2 + 0x8 + 14x3
2x3           3x2      -3x-1 + 0x0 + 14x0]    2x2

1, Check the compatibility( the forms are matching)
2. Find the shape of the output matrix. The matching dimension disappears, so the resulting shape is 2x2.
-Matices are nothing more than a collection of vectors. 
- When we have a dot product, we always multiply a row vector times a column vector.
-Note that the row vectors determine the row, column vectors determine the column.
- Compatibility: they need to have matching forms.

##### Scalar * Matrix

In [3]:
import numpy as np

A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

##### Matrix * Matrix

In [5]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [6]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

In [ ]:
# E.g 2

4x5 . 5x2 = 4x2  #compatible

3x4 . 2x3 = x # not compatible

### Why is Linear Algebra Useful

We've seen a lot of Matrix operation so far. Why then is LA useful?
There are many applications of LA. There are sevearl ones of high importance in Data science.
We'll explore 3 mtds in this lesson;

1.Vectorised code
2.Image recognition
3.Dimensionality reduction

#### Vectorised Code

Whenever we are using linear algebra to compute many values simultaneously,we call this Array programming or Vectorising code. It is much more faster.
We can reduce manual calculation of large data by creating a loop or using matrix operations. It contains inputs, weights coefficients and outputs. Numpy is optimised for performing this kind of operations, which greatly increases the computational efficiency of our code.

E.g
We can claim that the price of a house depends on its size. Let's take the eqn;
Price = 10,190 + 223 * house size
Suppose we have house sizes of 693,656,1060,487,1275 for 5 houses.
Plug in each size in the eqn and find the price of each house.
Calculating manually we have
10,190+223+693 = 164729 up to the 5th house.

Suppose we have 100 and above houses, it'll be quite tedious to calculate. To deal with that problem, we create a loop. We can iterate over the sizes, multiplying each of them by 223 + 10,190 ie
for i in range (100):
print (10,190 + 223 * size[i])

We will use a smarter option - Linear algebra.
A 5x2 matrix and a vector of length 2x1. The matrix contains a column of 1s and another with the house sizes. The vector contains the numbers from the eqn 10,190 and 223.

Whenever we're using linear algebra to compute many values simultaneously, we call this ARRAY PROGRAMMING or VECTORISING CODE.

In [ ]:
[1  693     [10190     [1*10,190 + 693*223      [164729
 1  656  .    223]   =  1*10,190 + 223*656       156478
 1  1060                1*10,190 + 223*1060   =  246570
 1  487                 1*10,190 + 223*487       118791
 1  1275]               1*10,190 + 223*1275]     294515]
     5x2       2x1         5x1                    5x1
    
    Input                  weights or coefficient   outputs
    
# No matter the number of inputs, we'll get as many outputs. The eqn does'nt change as it 
# contains only the 2 coefficients; 10,190 and 223.
# This concepts tiurns very helpful in our machine learning.

#### Image Recognition

In the last few years, deep learning and deep neural networks conquered image recognition. On the forefront is the CNNS (convolutional neural networks). The basic idea is; you can take a photo, feed it to the algorithm and classify it. 
E.g

1.the MNIST dataset where the task is to classify hand written digits.
2.CIFER 10 where the task is to classify animals and vehicles.
3.CIFER 100 where you have 100 difft classes of images.

The problem is that we can't just take a photo and give it to the computer, we must design a way to turn that photo into numbers in other to communicate the image to the computer.

Here's where LA comes in;
Each photo has some dimensions, say this photo is 400x400 pixels, each pixel is a coloured square. Enough pixels and Zoom options make our brain see these squres as an image rather than a collection of squares.

#### Dimesionality Reduction

Since we haven't seen Eigenvalues and Eigenvectors yet, let's develop some intuition.
Imagine we have a dataset with 3 variables. LA provides us with fast and efficient ways to transform our initial matrix from mx3 with the 3 variables x y z into a new mx2 matrix where the 2 variables are u&v.
How does that relate to the real world?
Imagine a survey of 50 qns, 3 of them are the ffg;

Please rate from 1 to 5

1.I feel comfortable around pple
2.I easily make friends
3.I like going out

These qns may seem difft, but in the general case, they aren't. They all measure your level of extroversion, so it makes sense to combine them.
That's where dimensionality reduction techniques and linear Algebra come in. Sometimes we have too many variables that are similar, so we reduce the number of variables to reduce the complexity of the problem.

In [1]:
import numpy as np

In [2]:
A = np.array([[1,-4],[-2,1]])
B = np.array([[0,3],[5,8]])

In [3]:
A

array([[ 1, -4],
       [-2,  1]])

In [4]:
B

array([[0, 3],
       [5, 8]])

In [5]:
A-B

array([[ 1, -7],
       [-7, -7]])

In [6]:
A+B

array([[ 1, -1],
       [ 3,  9]])

In [9]:
x = np.array([8,2,5,1])

In [10]:
x

array([8, 2, 5, 1])

In [11]:
x*2

array([16,  4, 10,  2])

In [12]:
x.T

array([8, 2, 5, 1])